# Site settings
title: Coding for Literature Majors
header-img: img/home-bg.png
email: cricky@flatironschool.com
copyright_name: crickycicchetti
description: > # this means to ignore newlines until "baseurl:"
  Learning code with Flatiron School's Web Development track. 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  crickycicchetti
learn_profile: crickycicchetti
email_username: cricky@flatironschool.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
